### ISSUE TITLE
Segmentation fault (core dumped) after run

### ISSUE THREAD

**Issue by AMBiuki** [p0l1t1c1an/Mines#1]
Hi, I just compiled your code successfully with:
[amb@dhcppc5 Mines]$ gcc `pkg-config --cflags --libs gtk+-3.0` Tile.c Board.c main.c
but running:
[amb@dhcppc5 Mines]$ ./a.out
caused `Segmentation fault (core dumped)` without showing any GUI. Can you help me? thx
Also how can I debug this project with vscode (vscode can't recognize any of gtk code)? I new to gtk and c debugging :)

**Comment by p0l1t1c1an** [comment]
Right now, I am actually rewriting this program, since it seems to only run on my Arch Linux machine. The program is actually Linux dependent because of the set_directory function in Tile.c, but I want it to work on a FreeBSD system I have. My intentions are to have the program not be stuck as Linux only and add a `Makefile` so you won't have to run gcc. As well, I'm restructuring the program to be more efficient, easier to read, and in general just make more sense. 

About the segmentation fault, use a program like `valgrind` to track where the segmentation fault is happening in the program and post the output here. It will help me out with seeing what wrong on other people's systems. 

As for using vscode, I would have no idea since I have never used visual studio. I use neovim with a few plugins for C/C++ and Java programming. I'm going to guess you have figured something out in the month you posted this. 

Sorry for seeing this about a month late.

**Comment by p0l1t1c1an** [comment]
I'm closing this issue as I have released my rewrite of the program. If you have issues with the program now, open a new issue.
